### ISSUE TITLE
Setup CI/CD for testing and building application.

### ISSUE THREAD

**Issue by fredriksvendsen** [it2901/Skrp#2]

**Comment by jfremstad** [comment]
To [upload releases](https://circleci.com/blog/publishing-to-github-releases-via-circleci/) on Github, we need to add a token to the project on circleci. I think only @YngveMolnes has access to do this.

The link above suggests using some tool to upload to github, but that seems more complex than necessary because one needs to share workspaces and use a container with go.

I think the easiest thing is to use curl after the buildstep.

**Comment by YngveMolnes** [comment]
- Set up packer for updating a VM-snapshot to include the latest artifacts
