### ISSUE TITLE
Setup unit testing for frontend

### ISSUE THREAD

**Issue by Allmeta** [it2901/Skrp#43]

**Comment by ghost** [comment]
You should target the pages with the data-cy attribute, as in data-cy="about" in your routing  instead of saying a[href="#/about"] in the cypress tests. 

read the image below 

<img width="729" alt="screen shot 2019-03-08 at 10 32 19" src="https://user-images.githubusercontent.com/22235649/54020268-a7a03780-418d-11e9-93c6-ae37504d4f71.png">
